[package]
name = "dusk-blindbid"
version = "0.3.0"
authors = ["CPerezz <carlos@dusk.network>", "Victor Lopez <victor@dusk.network>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
dusk-pki = {git = "https://github.com/dusk-network/dusk-pki", tag = "v0.3.0"}
poseidon252 = {git = "https://github.com/dusk-network/poseidon252", tag = "v0.13.0"}
dusk-plonk = {version = "0.3.3", features = ["trace-print"]}
num-bigint = "0.3.0"
num-traits = "0.2.11"
plonk_gadgets = {git = "https://github.com/dusk-network/plonk_gadgets", tag = "v0.4.2"}
thiserror = "1.0"
rand_core = "0.5.1"
lazy_static = "1.4.0"
rand = "0.7"
canonical = {version = "0.4", optional = true}
canonical_derive = {version = "0.4", optional = true}
microkelvin = {version = "0.5", optional = true}
nstack = {version = "0.6", optional = true}

[features]
canon = [
    "canonical",
    "canonical_derive",
    "nstack",
    "microkelvin",
    "dusk-plonk/canon",
    "dusk-pki/canon",
    "poseidon252/canon"
]
